services:

  laravel-docker:
    container_name: grics-laravel-docker
    build: .
    volumes:
      - ./laravel-app:/var/www/html
      - ./frontend:/var/www/html/public
    ports:
      - 9000:80
  
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grics
    ports:
    - 3306:3306
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1